docker-4 completed
Otus-DevOps-2022-11/Isuaven_microservices pull request #3
Opened 2023-04-16 19:10 UTC by Isuaven

# Выполнено ДЗ № 26

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Выполнено основное ДЗ
 - Изменён docker-compose под кейс с множеством сетей
 - Параметризирован docker-compose и создан .env файл под это
 - Изменено имя проекта с помощью переменной COMPOSE\_PROJECT\_NAME
 - Задание со \*: создан docker-compose.override.yml, который
  - Добавляет в каждое приложение volume
  - Запускает puma для руби в дебаг режиме с двумя воркерами

## Как запустить проект:
 - docker-compose up -d

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-04-16 19:10 UTC, Isuaven commented
Файл src/docker-compose.yml существует, я не понимаю почему тест падает на его поиске

2023-04-17 08:00 UTC, mrgreyves requested changes
Здравствуйте!
![image](https://user-images.githubusercontent.com/34331259/232422414-333a3566-675c-4682-aa26-8b3ca176164f.png)
Где он существует?

2023-04-17 08:18 UTC, Isuaven commented
@mrgreyves Сорян, не заметил, что он был почему-то в .gitignore. Либо случайно попал, либо с прошлых ДЗ там был указан. Залил, теперь фейлится на билде коммент модуля

2023-04-19 17:24 UTC, mrgreyves requested changes
Здравствуйте!
Стоит постараться пофиксить
Так как докерфайлы и прочее нам пригодятся

2023-04-22 11:19 UTC, Isuaven commented
@mrgreyves Пофиксил

2023-04-23 14:51 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь точно апрув ^_^

2023-04-23 17:30 UTC, merged